module.exports = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  SERVER_ERROR: 'SERVER_ERROR',
  AI_PARSING_ERROR: 'AI_PARSING_ERROR',
  AI_SERVICE_ERROR: 'AI_SERVICE_ERROR',
  AI_CONFIG_ERROR: 'AI_CONFIG_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  CORS_ERROR: 'CORS_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR'
};
